### PR TITLE
Master PR to test Layout Builder for YUSA WebServices profile

### PR DESCRIPTION
**Pull request by anpolimus**
## PR for testing Layout Builder migration

To spinup copy of this code run

```sh
composer create-project ycloudyusa/yusaopeny-project:dev-9.2.x-lb1 MY_PROJECT --no-interaction --no-dev
```

### CODE REVIEW

**Comment by anpolimus** [comment]
retest me please

**Comment by anpolimus** [comment]
retest me please

**Comment by podarok** [comment]
retest this please

**Comment by anpolimus** [comment]
retest this please

**Comment by anpolimus** [comment]
retest this please

**Comment by podarok** [comment]
image
@andrey_zb

**Comment by anpolimus** [comment]
retest this please

**Comment by mkdok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by anpolimus** [comment]
retest this please

**Comment by mkdok** [comment]
retest this please

**Comment by anpolimus** [comment]
retest this please

**Comment by mkdok** [comment]
retest this please

**Comment by mkdok** [comment]
retest this please

**Comment by mkdok** [comment]
retest this please

**Comment by mkdok** [comment]
retest this please

**Comment by mkdok** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by mkdok** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by mkdok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by mkdok** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by mkdok** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Pull request merged**
