### PR TITLE
Drupal core 10.1-10.2

### PR DESCRIPTION
**Pull request by podarok**
MERGE only after https://github.com/YCloudYUSA/yusaopeny/pull/170 merged and released!!!!

Original Issue, this PR is going to fix: [see comment](https://github.com/YCloudYUSA/yusaopeny/pull/72#issuecomment-1618183672)

Related issue https://github.com/YCloudYUSA/y_lb_demo_content/pull/43

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use 9.x-2.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] Try to use Conventional commit messages accordingly to the standard https://www.conventionalcommits.org/en/v1.0.0/#specification
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by podarok** [comment]
```
0;31m        " [notice] Performed install task: openy_discover_broken_paragraphs",[0m
[0;31m        " [notice] Performed install task: openy_fix_configured_paragraph_blocks",[0m
[0;31m        " [error]  TypeError: Drupal\\openy\\Form\\ThirdPartyServicesForm::__construct(): Argument #2 ($collection_optimizer) must be of type Drupal\\Core\\Asset\\JsCollectionOptimizerLazy, Drupal\\Core\\Asset\\JsCollectionOptimizer given, called in /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-profile/src/Form/ThirdPartyServicesForm.php on line 51 in Drupal\\openy\\Form\\ThirdPartyServicesForm->__construct() (line 40 of /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-profile/src/Form/ThirdPartyServicesForm.php) #0 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-profile/src/Form/ThirdPartyServicesForm.php(51): Drupal\\openy\\Form\\ThirdPartyServicesForm->__construct()",[0m
[0;31m        "#1 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/docroot/core/lib/Drupal/Core/DependencyInjection/ClassResolver.php(28): Drupal\\openy\\Form\\ThirdPartyServicesForm::create()",[0m
[0;31m        "#2 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(195): Drupal\\Core\\DependencyInjection\\ClassResolver->getInstanceFromDefinition()",[0m
[0;31m        "#3 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/docroot/core/includes/install.core.inc(961): Drupal\\Core\\Form\\FormBuilder->getFormId()",[0m
[0;31m        "#4 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/docroot/core/includes/install.core.inc(616): install_get_form()",[0m
[0;31m        "#5 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/docroot/core/includes/install.core.inc(569): install_run_task()",[0m
[0;31m        "#6 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/docroot/core/includes/install.core.inc(119): install_run_tasks()",[0m
[0;31m        "#7 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/drush/drush/includes/drush.inc(69): install_drupal()",[0m
[0;31m        "#8 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/drush/drush/includes/drush.inc(53): drush_call_user_func_array()",[0m
[0;31m        "#9 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/drush/drush/src/Commands/core/SiteInstallCommands.php(169): drush_op()",[0m
[0;31m        "#10 [internal function]: Drush\\Commands\\core\\SiteInstallCommands->install()",[0m
[0;31m        "#11 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/consolidation/annotated-command/src/CommandProcessor.php(276): call_user_func_array()",[0m
[0;31m        "#12 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\\AnnotatedCommand\\CommandProcessor->runCommandCallback()",[0m
[0;31m        "#13 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\\AnnotatedCommand\\CommandProcessor->validateRunAndAlter()",[0m
[0;31m        "#14 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(391): Consolidation\\AnnotatedCommand\\CommandProcessor->process()",[0m
[0;31m        "#15 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/symfony/console/Command/Command.php(312): Consolidation\\AnnotatedCommand\\AnnotatedCommand->execute()",[0m
[0;31m        "#16 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()",[0m
[0;31m        "#17 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand()",[0m
[0;31m        "#18 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()",[0m
[0;31m        "#19 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\\Component\\Console\\Application->run()",[0m
[0;31m        "#20 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\\Runtime\\Runtime->doRun()",[0m
[0;31m        "#21 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/drush/drush/drush.php(139): Drush\\Runtime\\Runtime->run()",[0m
[0;31m        "#22 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/drush/drush/drush(4): require('...')",[0m
[0;31m        "#23 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/bin/drush(120): include('...')",[0m
[0;31m        "#24 {main}. ",[0m
[0;31m        "TypeError: Drupal\\openy\\Form\\ThirdPartyServicesForm::__construct(): Argument #2 ($collection_optimizer) must be of type Drupal\\Core\\Asset\\JsCollectionOptimizerLazy, Drupal\\Core\\Asset\\JsCollectionOptimizer given, called in /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-profile/src/Form/ThirdPartyServicesForm.php on line 51 in /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-profile/src/Form/ThirdPartyServicesForm.php on line 40 #0 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-profile/src/Form/ThirdPartyServicesForm.php(51): Drupal\\openy\\Form\\ThirdPartyServicesForm->__construct()",[0m
[0;31m        "#1 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/docroot/core/lib/Drupal/Core/DependencyInjection/ClassResolver.php(28): Drupal\\openy\\Form\\ThirdPartyServicesForm::create()",[0m
[0;31m        "#2 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(195): Drupal\\Core\\DependencyInjection\\ClassResolver->getInstanceFromDefinition()",[0m
[0;31m        "#3 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/docroot/core/includes/install.core.inc(961): Drupal\\Core\\Form\\FormBuilder->getFormId()",[0m
[0;31m        "#4 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/docroot/core/includes/install.core.inc(616): install_get_form()",[0m
[0;31m        "#5 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/docroot/core/includes/install.core.inc(569): install_run_task()",[0m
[0;31m        "#6 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/docroot/core/includes/install.core.inc(119): install_run_tasks()",[0m
[0;31m        "#7 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/drush/drush/includes/drush.inc(69): install_drupal()",[0m
[0;31m        "#8 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/drush/drush/includes/drush.inc(53): drush_call_user_func_array()",[0m
[0;31m        "#9 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/drush/drush/src/Commands/core/SiteInstallCommands.php(169): drush_op()",[0m
[0;31m        "#10 [internal function]: Drush\\Commands\\core\\SiteInstallCommands->install()",[0m
[0;31m        "#11 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/consolidation/annotated-command/src/CommandProcessor.php(276): call_user_func_array()",[0m
[0;31m        "#12 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\\AnnotatedCommand\\CommandProcessor->runCommandCallback()",[0m
[0;31m        "#13 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\\AnnotatedCommand\\CommandProcessor->validateRunAndAlter()",[0m
[0;31m        "#14 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(391): Consolidation\\AnnotatedCommand\\CommandProcessor->process()",[0m
[0;31m        "#15 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/symfony/console/Command/Command.php(312): Consolidation\\AnnotatedCommand\\AnnotatedCommand->execute()",[0m
[0;31m        "#16 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()",[0m
[0;31m        "#17 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand()",[0m
[0;31m        "#18 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()",[0m
[0;31m        "#19 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\\Component\\Console\\Application->run()",[0m
[0;31m        "#20 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\\Runtime\\Runtime->doRun()",[0m
[0;31m        "#21 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/drush/drush/drush.php(139): Drush\\Runtime\\Runtime->run()",[0m
[0;31m        "#22 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/drush/drush/drush(4): require('...')",[0m
[0;31m        "#23 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-project/vendor/bin/drush(120): include('...')",[0m
[0;31m        "#24 {main}",[0m
[0;31m        " [warning] Drush command terminated abnormally."[0m
[0;31m    ],[0m
[0;31m    "stdout": "\n You are about to:\n * Create a sites/default/settings.php file\n * DROP all tables in your 'drupal4262' database.\n\n // Do you want to continue?: yes.                                              \n\nTypeError: Drupal\\openy\\Form\\ThirdPartyServicesForm::__construct(): Argument #2 ($collection_optimizer) must be of type Drupal\\Core\\Asset\\JsCollectionOptimizerLazy, Drupal\\Core\\Asset\\JsCollectionOptimizer given, called in /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-profile/src/Form/ThirdPartyServicesForm.php on line 51 in Drupal\\openy\\Form\\ThirdPartyServicesForm->__construct() (line 40 of /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-profile/src/Form/ThirdPartyServicesForm.php).",[0m
[0;31m    "stdout_lines": [[0m
[0;31m        "",[0m
[0;31m        " You are about to:",[0m
[0;31m        " * Create a sites/default/settings.php file",[0m
[0;31m        " * DROP all tables in your 'drupal4262' database.",[0m
[0;31m        "",[0m
[0;31m        " // Do you want to continue?: yes.                                              ",[0m
[0;31m        "",[0m
[0;31m        "TypeError: Drupal\\openy\\Form\\ThirdPartyServicesForm::__construct(): Argument #2 ($collection_optimizer) must be of type Drupal\\Core\\Asset\\JsCollectionOptimizerLazy, Drupal\\Core\\Asset\\JsCollectionOptimizer given, called in /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-profile/src/Form/ThirdPartyServicesForm.php on line 51 in Drupal\\openy\\Form\\ThirdPartyServicesForm->__construct() (line 40 of /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build4262/yusaopeny-profile/src/Form/ThirdPartyServicesForm.php)."[0m
[0;31m    ][0m
[0;31m}[0m
```

**Comment by podarok** [comment]
```
In FieldStorageConfigStorage.php line 167:",
        "                                                                               ",
        "  Unable to determine class for field type 'colorapi_color_field' found in th  ",
        "  e 'field.storage.0' configuration                                            ",
        "                                                                               ",
        "",
        "In DiscoveryTrait.php line 53:",
        "                                                                               ",
        "  The \"colorapi_color_field\" plugin does not exist. Valid plugin IDs for Drup  ",
        "  al\\Core\\Field\\FieldTypePluginManager are: datetime, daterange, entity_refer  ",
        "  ence_revisions, file_uri, file, image, layout_section, link, metatag, list_  ",
        "  integer, list_string, list_float, path, plugin:plugin_selector, plugin:enti  ",
        "  ty_reference_selector, plugin:field_widget, plugin:field_formatter, plugin:  ",
        "  archiver, plugin:action, plugin:menu_link, plugin:menu_local_action, plugin  ",
        "  :menu_local_task, plugin:menu_lcontextual_link, plugin:display_variant, plu  ",
        "  gin:queue_worker, plugin:mail, plugin:condition, plugin:element, plugin:blo  ",
        "  ck, plugin:ckeditor_plugin, plugin:editor, plugin:filter, plugin:image_effe  ",
        "  ct, plugin:language_negotiation_method, plugin:migrate_process, plugin:migr  ",
        "  ate_destination, plugin:migrate_id_map, plugin:migration, plugin:tour_tip,   ",
        "  plugin:views_access, plugin:views_area, plugin:views_argument, plugin:views  ",
        "  _argument_default, plugin:views_argument_validator, plugin:views_cache, plu  ",
        "  gin:views_display_extender, plugin:views_display, plugin:views_exposed_form  ",
        "  , plugin:views_field, plugin:views_filter, plugin:views_join, plugin:views_  ",
        "  pager, plugin:views_query, plugin:views_relationship, plugin:views_row, plu  ",
        "  gin:views_sort, plugin:views_style, plugin:views_wizard, plugin:ws_style, p  ",
        "  lugin:ws_style_option, plugin:paragraphs.paragraphs_behavior, telephone, te  ",
        "  xt_long, text_with_summary, text, string, uuid, timestamp, changed, languag  ",
        "  e, string_long, email, map, float, entity_reference, boolean, uri, integer,  ",
        "   created, decimal, password                                                  ",
        "                                                                               "
    ],
    "stdout": " You are about to:\n * Create a sites/default/settings.php file\n * DROP all tables in your 'drupal4271' database.\n\n // Do you want to continue?: yes.                                              ",
    "stdout_lines": [
        " You are about to:",
        " * Create a sites/default/settings.php file",
        " * DROP all tables in your 'drupal4271' database.",
        "",
        " // Do you want to continue?: yes.                                              "
    ]
```

**Comment by podarok** [comment]
Upgrade path seems like OK 
image

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
YES!
image

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
image
THank you @svicervlad

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by rollki** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by rollki** [comment]
retest this please

**Comment by rollki** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by podarok** [comment]
image

**Comment by podarok** [comment]
@AnastasiiaPys I'm ready to merge this. Once you confirm tickets in QA column for core 10.2 validated

**Comment by podarok** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
tagged https://github.com/YCloudYUSA/yusaopeny/releases/tag/10.3.3

**Pull request merged**
