### PR TITLE
feat: Add Y PEF Schedule app

### PR DESCRIPTION
**Pull request by podarok**
Original Issue, this PR is going to fix: REPLACE WITH A LINK TO ISSUE ( publicly available )

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use `main` branch. We'll tag for release if the bug is critical ASAP or tag for release next bug fix release until the critical issue arrives.

## Steps for review

- [ ] Please provide steps for review here.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] Try to use Conventional commit messages accordingly to the standard https://www.conventionalcommits.org/en/v1.0.0/#specification
- [ ] [Documentation](https://github.com/ycloudyusa/yusaopeny/tree/main/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ycloudyusa/yusaopeny/blob/main/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with an account on drupal.org, otherwise, you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ycloudyusa/yusaopeny/blob/main/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by anpolimus** [comment]
I think, it is better to have this component as separate component like Activity Finder or Virtual Y that could be required by Y that really needs it.

**Comment by anpolimus** [comment]
Yes, you are right, AF is not separate now.
We could discuss it on one of our next calls.

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by rollki** [comment]
## Steps to reproduce:
1. Enable the y_pef_schedule module on the extensions page
2. Go to the branch selection page (`/admin/openy/branch-schedules`), you can also go to this page from the administrative menu (Content -> Schedules Calendar)
3. Choose any available branch
4. You should now be able to view the calendar including:
- download the current view in PDF format
- filter by category (by pressing the Legend+ button)
- change the view from weekly to daily
- switch between weeks
- create events from the calendar (by analogy with Google Calendar), including a series of events (when creating a series of events, only one event is displayed, for correct display you need to reload the page - this should also be discussed)
- view basic information about the event by clicking on it
- edit the event from the popover, after clicking on the event
- drag an event within one day (for other days, dragging is disabled and must be discussed)

**Comment by podarok** [comment]
retest this please

**Comment by rollki** [comment]
@podarok 
I'm not sure if the latest version of the module got into this new build, I can't check it.

**Comment by podarok** [comment]
retest this please

**Comment by rollki** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by rollki** [comment]
retest this please

**Comment by rollki** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by rollki** [comment]
retest this please

**Comment by rollki** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by rollki** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by rollki** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by rollki** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by AnastasiiaPys** [comment]
retest this please

**Comment by podarok** [comment]
I merged it @froboy @AnastasiiaPys 
But we need to discuss if this module required in any of profile variations or should stay as it is now

**Pull request merged**
