### PR TITLE
DS-1602 feat: Add initial Small Y functionality.

### PR DESCRIPTION
**Pull request by froboy**
[Small Y Component Prep](https://yusa.atlassian.net/browse/DS-1602)

Requires https://www.drupal.org/project/ws_small_y/issues/3469220

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use `main` branch. We'll tag for release if the bug is critical ASAP or tag for release next bug fix release until the critical issue arrives.

## Steps for review

- [ ] `drush -vy si openy openy_configure_profile.preset=small_y openy_theme_select.theme=openy_carnation openy_terms_of_use.agree_openy_terms=1 install_configure_form.enable_update_status_emails=NULL --account-name=admin --account-pass=admin --site-name='YMCA Website Services sandbox'`

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] Try to use Conventional commit messages accordingly to the standard https://www.conventionalcommits.org/en/v1.0.0/#specification
- [ ] [Documentation](https://github.com/ycloudyusa/yusaopeny/tree/main/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ycloudyusa/yusaopeny/blob/main/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with an account on drupal.org, otherwise, you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ycloudyusa/yusaopeny/blob/main/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by froboy** [comment]
SCR-20240820-myao
@podarok the installer isn't testable due to a permissions error.

**Review by svicervlad — APPROVED** [review]

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
```
Unable to install modules openy_txnm_color, openy_node_alert, google_tag, g  ",
        "  oogle_analytics, easy_breadcrumb, openy_block_basic, openy_block_featured_h  ",
        "  ighlights, openy_block_menu, openy_code_block, openy_prgf_1c, openy_prgf_2c  ",
        "  , openy_prgf_3c, openy_prgf_4c, openy_prgf_banner, openy_prgf_code_block, o  ",
        "  peny_prgf_faq, openy_prgf_featured_highlights, openy_prgf_gallery, openy_pr  ",
        "  gf_grid_content, openy_prgf_promo_card, openy_prgf_simple_content, openy_pr  ",
        "  gf_small_banner, openy_prgf_teaser, openy_block_branch_contacts_info, openy  ",
        "  _ckeditor, openy_block_branch_amenities, openy_loc_branch, openy_prgf_ameni  ",
        "  ties, openy_prgf_loc_finder, openy_prgf_location_by_amenities, openy_field_  ",
        "  hours, openy_field_custom_hours, openy_field_holiday_hours, openy_loc_facil  ",
        "  ity, openy_loc_filter, scheduler, openy_google_search, simple_sitemap, ws_s  ",
        "  mall_y, openy_gtranslate, openy_prgf_webform, y_lb, lb_accordion, y_lb_arti  ",
        "  cle, lb_branch_amenities_blocks, lb_branch_hours_blocks, lb_branch_social_l  ",
        "  inks_blocks, lb_cards, lb_carousel, ws_code_block, ws_event, lb_grid_cta, l  ",
        "  b_hero, lb_related_articles_blocks, lb_related_events_blocks, lb_modal, ope  ",
        "  ny_map_lb, lb_partners_blocks, lb_ping_pong, lb_promo, lb_simple_menu, lb_s  ",
        "  taff_members_blocks, lb_statistics, lb_table, ws_lb_tabs, lb_testimonials,   ",
        "  lb_webform, y_camp, y_facility, y_lb_main_menu_cta_block, layout_builder_re  ",
        "  strictions_by_region, lb_grid_icon, lb_donate, y_donate, y_program, y_progr  ",
        "  am_subcategory due to missing modules ws_small_y
```

**Comment by podarok** [comment]
Continue here https://github.com/YCloudYUSA/yusaopeny/pull/210
PR builder can't build proper site from forks, due to composer complexities

**Pull request merged**
