### PR TITLE
feat!: Drupal 10 core bugs triage

### PR DESCRIPTION
**Pull request by podarok**
To get all code locally, run

```sh
composer create-project ycloudyusa/yusaopeny-project:dev-9.2.x-init-d10 drupal10 --no-interaction --no-dev
```

Blockers

- [x] https://www.drupal.org/i/3248715
- [x] https://www.drupal.org/project/activenet/releases/1.0.3
- [x] https://www.drupal.org/project/advanced_help_block/releases/1.0.3
- [x] https://www.drupal.org/project/social_feed_fetcher/releases/3.0.x-dev
- [x] https://www.drupal.org/project/openy_carnation/releases/2.0.12
- [x] https://www.drupal.org/project/social_feed_fetcher/releases/3.0.1
- [x] https://www.drupal.org/project/social_feed_fetcher/releases/3.0.2
- [x] https://github.com/samoritano/linkedin-api-php-client/pull/2
- [x] https://www.drupal.org/project/openy_daxko2/releases/1.0.3
- [x] https://www.drupal.org/project/upgrade_tool/issues/3299386
- [x] https://www.drupal.org/project/views_field_formatter/issues/3290477#comment-14708680
- [x] https://github.com/open-y-subprojects/openy_features/pull/22
- [x] https://www.drupal.org/project/daxko/releases/1.0.3
- [x] https://www.drupal.org/project/daxko/releases/1.0.4
- [x] https://www.drupal.org/project/focal_point/issues/3295940#comment-14695285
- [x] https://www.drupal.org/project/personify/releases/1.0.3
- [x] https://www.drupal.org/project/program_search/releases/1.0.2
- [x] https://www.drupal.org/project/openy_socrates/releases/1.0.3
- [x] https://github.com/open-y-subprojects/openy_features/releases/tag/1.5.14
- [x] https://www.drupal.org/project/openy_mappings/releases/1.0.3
- [x] https://www.drupal.org/project/openy_gtranslate/releases/1.0.3
- [x] https://www.drupal.org/project/draggableviews/releases/2.0.2
- [x] https://www.drupal.org/project/openy_er/releases/1.0.3
- [x] https://www.drupal.org/project/openy_branch_selector/releases/1.0.4
- [x] https://www.drupal.org/project/openy_addthis/releases/1.0.4
- [x] https://www.drupal.org/project/simple_menu_icons/releases/3.0.0
- [x] https://github.com/open-y-subprojects/openy_features/releases/tag/1.5.15
- [x] https://www.drupal.org/project/libraries/releases/4.0.0
- [x] https://github.com/open-y-subprojects/openy_focal_point/releases/tag/1.0.1
- [x]  "drupal/token",
- [x]             "drupal/entity_embed",
- [x]             "drupal/easy_breadcrumb",
- [x]             "drupal/jquery_ui",
- [x]             "drupal/jquery_ui_slider",
- [x]             "drupal/video_embed_field",
- [x]             "drupal/config_update",
- [x]             "drupal/token_filter",
- [x]             "drupal/rabbit_hole",
- [x]             "drupal/media_entity_video",
- [x]             "drupal/image_widget_crop",
- [x]             "drupal/features",
- [x]             "drupal/editor_advanced_link",
- [x]             "drupal/domain",
- [x]             "drupal/domain_theme_switch",
- [x]             "drupal/views_block_filter_block",
- [x]             "drupal/focal_point",
- [x]             "drupal/fontyourface",
- [x]             "drupal/jquery_ui_tooltip",
- [x]             "drupal/jquery_ui_tabs",
- [x]             "drupal/geysir", see https://www.drupal.org/project/geysir/issues/3297304#comment-14946839
- [x]             "drupal/css_editor",
- [x]             "drupal/geolocation",
- [x]             "drupal/webform",
- [x]             "drupal/csv_serialization",
- [x]             "drupal/google_tag",
- [x]             "drupal/datalayer"
- [x] drupal/protected_pages
- [x] https://www.drupal.org/project/lb_claro

### CODE REVIEW

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by mkdok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
retest this please

**Pull request merged**
