### PR TITLE
feat: openy_features with Utility Menu

### PR DESCRIPTION
**Pull request by podarok**
Original Issue, this PR is going to fix: https://yusaslackinstance.slack.com/archives/C03E6SQQ0Q5/p1726582566750179?thread_ts=1726582450.933909&cid=C03E6SQQ0Q5

```
Installing drupal/diff (1.7.0): Extracting archive
  - Installing drupal/ckeditor5_font (1.1.2-beta1): Extracting archive
  - Installing open-y-subprojects/openy_features (3.3.3): Extracting archive
  - Installing open-y-subprojects/openy_daxko_gxp_syncer (1.2.1): Extracting archive
  - Installing open-y-subprojects/common_scss (dev-main 6209485): Extracting archive
```

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use `main` branch. We'll tag for release if the bug is critical ASAP or tag for release next bug fix release until the critical issue arrives.

## Steps for review

- [ ] Please provide steps for review here.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] Try to use Conventional commit messages accordingly to the standard https://www.conventionalcommits.org/en/v1.0.0/#specification
- [ ] [Documentation](https://github.com/ycloudyusa/yusaopeny/tree/main/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/>Steps for review
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ycloudyusa/yusaopeny/blob/main/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with an account on drupal.org, otherwise, you won't get commits there. <br/>drupal.org email
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ycloudyusa/yusaopeny/blob/main/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### CODE REVIEW

**Comment by podarok** [comment]
retest this please

**Comment by podarok** [comment]
```
">  [error]  Configuration <em class=\"placeholder\">core.entity_view_display.node.lb_event.default</em> depends on the <em class=\"placeholder\">system.menu.utility</em> configuration that will not exist after import. ",
        ">  [error]  Update failed: y_lb_article_update_91001 ",
        ">  [notice] Update started: admin_toolbar_update_8003",
        ">  [notice] Update completed: admin_toolbar_update_8003",
        ">  [notice] Update started: field_group_update_8303",
        ">  [notice] Update completed: field_group_update_8303",
        ">  [notice] Update started: lb_cards_update_9012",
        ">  [error]  Configuration <em class=\"placeholder\">core.entity_view_display.node.lb_event.default</em> depends on the <em class=\"placeholder\">system.menu.utility</em> configuration that will not exist after import. ",
        ">  [error]  Update failed: lb_cards_update_9012 ",
        ">  [notice] Update started: lb_hero_update_10002",
        ">  [error]  Configuration <em class=\"placeholder\">core.entity_view_display.node.lb_event.default</em> depends on the <em class=\"placeholder\">system.menu.utility</em> configuration that will not exist after import. ",
        ">  [error]  Update failed: lb_hero_update_10002 ",
        ">  [notice] Update started: lb_ping_pong_update_9002",
        ">  [error]  Configuration <em class=\"placeholder\">core.entity_view_display.node.lb_event.default</em> depends on the <em class=\"placeholder\">system.menu.utility</em> configuration that will not exist after import. ",
        ">  [error]  Update failed: lb_ping_pong_update_9002 ",
        ">  [notice] Update started: link_attributes_update_9001",
        ">  [notice] Update completed: link_attributes_update_9001",
        ">  [notice] Update started: openy_calc_update_9001",
        ">  [notice] Update completed: openy_calc_update_9001",
        ">  [notice] Update started: openy_editor_update_91002",
        ">  [warning] You have manual updated editor.editor.full_html config from Open Y profile.",
        ">  [notice] Update completed: openy_editor_update_91002",
        ">  [notice] Update started: openy_media_image_update_10001",
        ">  [warning] You have manual updated core.entity_view_display.media.image.embedded_full config from Open Y profile.",
        ">  [warning] You have manual updated core.entity_view_display.media.image.embedded_half config from Open Y profile.",
        ">  [notice] Update completed: openy_media_image_update_10001",
        ">  [notice] Update started: openy_prgf_mbrshp_calc_update_10101",
        ">  [error]  Configuration <em class=\"placeholder\">core.entity_view_display.node.lb_event.default</em> depends on the <em class=\"placeholder\">system.menu.utility</em> configuration that will not exist after import. ",
        ">  [error]  Update failed: openy_prgf_mbrshp_calc_update_10101 ",
        ">  [notice] Update started: ws_event_update_9025",
        ">  [notice] Update completed: ws_event_update_9025",
        ">  [notice] Update started: y_branch_update_9011",
        ">  [notice] Update completed: y_branch_update_9011",
        ">  [notice] Update started: y_camp_update_9015",
        ">  [notice] Update completed: y_camp_update_9015",
        ">  [notice] Update started: y_facility_update_9006",
        ">  [notice] Update completed: y_facility_update_9006",
        ">  [notice] Update started: y_lb_update_9016",
        ">  [notice] Update completed: y_lb_update_9016",
        ">  [notice] Update started: y_lb_main_menu_cta_block_update_10001",
        ">  [notice] Update completed: y_lb_main_menu_cta_block_update_10001",
        ">  [notice] The file public://css/menu_icons.css was not deleted because it does not exist.",
        ">  [notice] The file public://css/menu_icons.css was not deleted because it does not exist.",
        " [error]  Update aborted by: y_lb_article_update_91001, lb_cards_update_9012, lb_hero_update_10002, lb_ping_pong_update_9002, openy_prgf_mbrshp_calc_update_10101 ",
        " [error]  Finished performing updates. ",
```

@froboy

**Comment by froboy** [comment]
@podarok looks like I have to go back and do the `config/outdated` thing again. I've added this code in all of the new updates:

```
  $moduleHandler = \Drupal::service('module_handler');
  if (!$moduleHandler->moduleExists('openy_menu_utility')) {
    \Drupal::service('module_installer')->install(['openy_menu_utility']);
  }
```
but updates are actually failing on a previous update which is pulling in the new config. I'll be back in... a few hours. 😭

**Comment by froboy** [comment]
Pushed two fixes:
- https://www.drupal.org/project/y_lb_article/releases/1.2.19
- https://www.drupal.org/project/ws_event/releases/1.4.17

retest this please

**Comment by froboy** [comment]
retest this please

**Comment by froboy** [comment]
SCR-20240918-khjt
Utility menu appears as expected on upgrade path. Not added to existing pages. 

Waiting for full install to check demo content.

**Comment by podarok** [comment]
Good progress @froboy

**Comment by froboy** [comment]
SCR-20240918-mnyy

**Comment by froboy** [comment]
Upgrade path and new install are completing successfully!

**Pull request merged**
